build:
    environment:
        php: '7.3.0'
            
    project_setup:
        before:
            - mysql -e "CREATE DATABASE IF NOT EXISTS store_db"
            
    tests:
        override:
            - php-scrutinizer-run
            -
                command: vendor/bin/phpunit --coverage-clover=coverage
                coverage:
                    file: coverage.xml
                    format: clover

before_commands:
    - "composer install --prefer-source"
    
tools:
    php_code_coverage:
        test_command: vendor/bin/phpunit

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*