language: php

php:
  - '7.2'
  - '7.3'

services:
  - mysql
  
before_script:
  - composer self-update
  - composer --version
  
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `store_db`;'

install:
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v